<html>  
<head>         
<meta http-equiv="content-type" content="text/html;charset=utf8">  
</head>  
<body>           
    <b>Dear Administrator</b>
<h2>${Subject}</h2>
<br>
<p>User Contact Details: </p>
<p>User name: ${UserName}</p>
<p>User email: ${UserEmail}</p>
<p>User Phone: ${UserPhone}</p>
<br>
<p>The message:</p>

<p>
 ${Message}
</p>
 
<br>
<p>Thank you,</p>
 
<b>${AppName} - Contact Us Service</b>
<p><b>NOTE:</b> Please do not reply to this message, which was automatically generated by the system. Mail sent to this address cannot be answered.</p>
</body>  
</html>  