<html>  
<head>         
<meta http-equiv="content-type" content="text/html;charset=utf8">  
</head>  
<body>           
    <b>Dear Administrator</b>

    <p>You have received an email from the ${SiteName} - ${AppName} Contact Us Service. Please see the details below:</p>
    <br/>

    <p>Subject: ${Subject}</p>
    <p>User name: ${UserName}</p>
    <p>User email: ${UserEmail}</p>
    <p>User Phone: ${UserPhone}</p>
    <br>
    <p>The message:</p>
    <p>
     ${Message}
    </p>

    <br>
    <p>Thank you,</p>

    <b>${AppName} - Contact Us Service</b>
    <p><b>NOTE:</b> This mail was automatically generated by the system.</p>
</body>  
</html>  