<html>  
<head>         
<meta http-equiv="content-type" content="text/html;charset=utf8">  
</head>  
<body>           
     <b>Dear ${RegisteredUser}</b>
 		
 <p>Your registered account has been rejected by the system administrator at ${SiteName} - ${AppName}.</p>
 <br>
 <p>Your registration details are as the following:
 <br>
 <p>User name: ${RegisteredUser}</p>
 <p>Registered email: ${UserEmail}</p>
 <p>Organization: ${Organization}</p>
 <br>

 <p><b>NOTE:</b> any question about registration, please contact with the system administrator</p>
 <br>

<p>Thank you,</p>
 
<b>${AppName} - User Registration Service</b> 
<p><b>NOTE:</b> Please do not reply to this message, which was automatically generated by the system. Mail sent to this address cannot be answered.</p>
</body>  
</html>  