<html>  
<head>         
<meta http-equiv="content-type" content="text/html;charset=utf8">  
</head>  
<body>           
     <b>Dear ${userEmail},</b>
 		
<p>We received your request for resetting your ${SiteName} - ${AppName} password. To confirm your request and reset your password, follow the instructions below:</p> 

<span style="color:blue; font-size:14px;">CONFIRM REQUEST AND RESET PASSWORD</span>
<br>
 
<p>1. Copy the following web address:</p>
<p>
<a href="${resetPasswdURL}">${resetPasswdURL}</a>
</p>
 
<p><span style="color:blue; font-size:14px;">IMPORTANT:</span>  Because fraudulent ("phishing") e-mail often uses misleading links, We recommends that you do not click links in e-mail, but instead copy and paste them into your browsers, as described above.</p>
 
<p>2. Open your web browser, paste the link in the address bar, and then press ENTER.</p>
 
<p>3. Follow the instructions on the web page that opens.</p>
 
 <br>
  
<p>Thank you,</p>
 
<b>${AppName} - User Registration Service</b> 
<p><b>NOTE:</b> Please do not reply to this message, which was automatically generated by the system. Mail sent to this address cannot be answered.</p>
</body>  
</html>  