<html>
<head>
    <meta http-equiv="content-type" content="text/html;charset=utf8">
    <style type="text/css">
        .result{
            width: 800px;
        }
        .div_msg{
            margin: 4px auto;
            border-top: solid 1px #E1E8F0;
            border-bottom: solid 1px #E1E8F0;
        }
        .div_site{
            color: gray;
            font-size: 1.0em;
            margin: 5px auto;
        }
        .note{
            margin: 5px auto;
            font-size: 0.9em;
            color: gray;
        }

    </style>
</head>
<body>
<b>Dear ${RegisteredUser}</b>,
<br>
<p>Transcript Factor Importing Results:</p>
<div class="result">
    <div class="div_msg">
        <p>File Name: ${tfSiteName}</p>
        <p>${ImportingMsg}.</p>
    </div>
</div>
<div class="div_site">${SiteName}</div>
<b>${AppName} - TfSite Importing Service</b>
<div class="note"><b>NOTE:</b> Please do not reply to this message, which was automatically generated by the system. Mail sent to this address cannot be answered.</div>
</body>
</html>