<html>  
<head>         
<meta http-equiv="content-type" content="text/html;charset=utf8">  
</head>  
<body>           
     <b>Dear Administrator</b>
 		
 <p>${RegisteredUser} registered an account at ${SiteName} - ${AppName} with the following details:</p>
 <br>
 <p>User name: ${RegisteredUser}</p>
 <p>Registered email: ${UserEmail}</p>
 <p>Organization: ${Organization}</p>
 <br>
<p>To activate user registration, please follow the instructions below:</p> 

<span style="color:blue; font-size:14px;">ACTIVATE USER REGISTRATION AND ACCOUNT</span>
<br>
 
<p>1. Copy the following web address:</p>
<p>
<a href="${ActivationURL}">${ActivationURL}</a>
</p>
 
<p><span style="color:blue; font-size:14px;">IMPORTANT:</span>  Because fraudulent ("phishing") e-mail often uses misleading links, We recommends that you do not click links in e-mail, but instead copy and paste them into your browsers, as described above.</p>
 
<p>2. Open your web browser, paste the link in the address bar, and then press ENTER.</p>
 
<p>3. Follow the instructions on the web page that opens.</p>
 
 <br>
  
<p>Thank you,</p>
 
<b>${AppName} - User Registration Service</b> 
<p><b>NOTE:</b> Please do not reply to this message, which was automatically generated by the system. Mail sent to this address cannot be answered.</p>
</body>  
</html>  